### PR TITLE
Added Synchronized Charts

### PR DESCRIPTION
**Pull request by 4n0nD3v3l0p3r**
Added ability to use synchronized charts
setId must be unique for each chart in setGroup
see documentation - https://apexcharts.com/javascript-chart-demos/line-charts/syncing-charts/

### CODE REVIEW

**Comment by appreciated** [comment]
First of all, thank you very much for your addition! 

I found "one hair in the soup", would it be possible to format this PR using the default IntelliJ formatter? If I reviewed this correctly this PR currently contains ~360 Line removals/additions that are not necessary. 
The final PR should contain about 50-100 new Lines and very little deletions.

**Comment by 4n0nD3v3l0p3r** [comment]
No no thank You for the initial plugin !

Sure I’ll reformat the PR - I use eclipse, which auto formatted the classes differently hence the large unnecessary changes :-/

**Comment by appreciated** [comment]
Why closing this issue? 🙂

**Comment by 4n0nD3v3l0p3r** [comment]
reformatted code :)

**Comment by appreciated** [comment]
Wow well done! 😃

**Pull request merged**
