### PR TITLE
treemap Type

### PR DESCRIPTION
**Pull request by andreika63**

### CODE REVIEW

**Comment by andreika63** [comment]
https://apexcharts.com/docs/options/plotoptions/heatmap/
by the way, new options was added to heatmap
`reverseNegativeShade useFillColorAsStroke`

**Comment by Markeey** [comment]
Will this change be released soon?

**Comment by appreciated** [comment]
@Markeey have you tried 24.0.0. If I'm not mistaken, this change should already be included.

**Comment by Markeey** [comment]
Perfect! Thank you very much for your quick reply. I didn't know that the 24.0.0 version was already released:
https://github.com/appreciated/apexcharts-flow/releases

**Pull request merged**
