### PR TITLE
Adding Support for combining line Charts with others #32

### PR DESCRIPTION
**Pull request by maupoc**
Hello,

i added support for combining line, area and column Charts freely.
Additional to that I changed Fill & FillBuilder to accept multiple inputs to configure each chart seperatly.
I also added 3 examples to show the usage.

For future adds:
I couldn´t get Scatter Charts with a line chart working and 
the other config options are not yet ready to configure multiple Charts differently.

Sincerely
Maurice Pochzosz

### CODE REVIEW

**Comment by appreciated** [comment]
> i added support for combining line, area and column Charts freely.
> Additional to that I changed Fill & FillBuilder to accept multiple inputs to configure each chart seperatly.

Nice!

> I also added 3 examples to show the usage.

Thank you very much!

> For future adds:
> I couldn´t get Scatter Charts with a line chart working and
> the other config options are not yet ready to configure multiple Charts differently.

Hmm 🤔 maybe it isn't supported?

**Comment by maupoc** [comment]
It should be supported as it is documented [here](https://apexcharts.com/javascript-chart-demos/mixed-charts/line-scatter/)
but it´s strange that it is not listed [here](https://apexcharts.com/javascript-chart-demos/mixed-charts/) as well.

**Comment by appreciated** [comment]
So I added now support for the missing scatter + line chart sorry for the delay in release, but some more tweaks were necessary.

**Comment by appreciated** [comment]
[2.0.0.beta7 is now available](https://vaadin.com/directory/component/apexchartsjs/2.0.0.beta7)

**Pull request merged**
