### PR TITLE
#91 ApexChartsBuilder should accept multiple Y axis like corresponding JavaScript API

### PR DESCRIPTION
**Pull request by error08**

### CODE REVIEW

**Comment by error08** [comment]
@appreciated Please can you create a new version e.q. beta13? I need that feature and want to use the official version.

**Comment by appreciated** [comment]
@error08 I am currently on it!

**Comment by appreciated** [comment]
You almost sneaked a regression issue into the next version. I recommend running the demo before creating a PR. But still, thank you very much for your contribution 🙂!

**Comment by error08** [comment]
Sorry for that! Iuse that code in my project and in principial it works. Maybe I missed a side effect.

**Comment by appreciated** [comment]
No worries

**Pull request merged**
