### PR TITLE
apexDev

### PR DESCRIPTION
**Pull request by dboehm**
This is a FIX and pull request to handle formatting of the Xaxis - timestamp in 'datetime' ApexChart - Types. 
The JSON-encoding and transfer was not correctly implemented  for  
a) the formatter - String 
b) the DatetimeFormatter objects
c) and for the Xaxis at all because of a lacking getter.

Our need was to update the chart every second interval to show and include a stable and walking high-resolution timescale.

FIXED by this pull request, 
Bildschirmfoto vom 2020-08-17 13-39-23
Bildschirmfoto vom 2020-08-17 13-40-21

Using this FIX it was possible to scale the datetime Xaxis using the formatter seen above.
CAUTION: It is necessary to truncate the timestamp before transmitting to the browser by 

- `offsetTime.truncatedTo(ChronoUnit.SECONDS);`

to get a stable walk every second.

Bildschirmfoto vom 2020-08-17 13-57-14

Without this FIX using the same code the scaling is useless as seen below. 
Bildschirmfoto vom 2020-08-17 14-03-34

This is, because JSON-objects formatter and datetimeformatter are not transmitted to apexchart.js.

Please feel free for every question.

Kind regards 
Detlef

### CODE REVIEW

**Comment by appreciated** [comment]
Hi @dboehm, 
Thank you very much for your pull request!
Your contribution looks good. I have found a small issue with it.
You updated the Vaadin version to 16, at the same time you increased the version indicating that this is only a minor update. While from a feature point of view this is totally correct, this will cut off some users that are still using V14.

Ideally, the following pattern should be used instead:
2.0 -> V14
...
6.0 -> V18
But while thinking about it using similar versioning to Vaadin actually makes more sense and will not confuse users. 
To close this as soon as possible, just follow the schema above for now.

I would like to include this commit in the next 2.0 version. Please revert the Vaadin version to the most current LTS version.
I will create a V16 branch with the correct version and release two new versions. 

Note: By the way, it is possible to add a note "closes #78" somewhere. As soon as the PR gets merged, the related issue will be closed automatically.

**Comment by dboehm** [comment]
Hi @appreciated,
I totally agree! I mixed it up - which was a thought I got also yesterday in my mind in the evening while @appreciated :+1: the after-work-time :-) 
Should I also stick to <version>2.0.0.beta9</version> to have a silent upgade ? Or would you like to increment me the beta version ? 
 
Cool thanks and cheers 
dboehm

**Comment by appreciated** [comment]
No problem 😉. Thats what reviews are made for. 
> Should I also stick to 2.0.0.beta9 to have a silent upgade ? Or would you like to increment me the beta version ?

Since the Vaadin directory does not allow silent upgrades from my knowledge, the only option is to increment the version.

**Comment by dboehm** [comment]
Nevertheless 'The latest stable release of Vaadin 14 is 14.3.3.' it is up to you to increment the version.

**Comment by rucko24** [comment]
Hi, How are you @dboehm @appreciated ?

I have precisely the need to implement the same case.

**View with Scheulder update every 2 seconds**

https://github.com/rucko24/nodemcu-with-flow/blob/bd799c3af612a47ab8e8cc199a1ae81c3dc956ea/src/main/java/com/example/application/views/dht22am2302/DHT22AM2302View.java

- I don't really understand where this is going, `offsetTime.truncatedTo(ChronoUnit.SECONDS);`
- And this `withCssClass("timeformat")` maybe, some styles.

Actually I have advanced more because before I could not achieve that in the XAxys, although I need to draw the series
image

Will they still have a test on how to use this?

**regards...**

**Comment by appreciated** [comment]
@rucko24 I am pretty well, pretty busy at the moment. I hope you are well too. Have you had a look at the [stream example](https://github.com/appreciated/apexcharts-flow/blob/master/src/test/java/com/github/appreciated/apexcharts/examples/stream/StreamingDataExampleView.java)?

**Comment by rucko24** [comment]
Hi, 

That example works fine with randon values, but the problem comes when trying to show the time in the XAxys.

But is it possible that with the **XAxys** it shows, for example, a format like **HH:mm:ss?**

```java
public class StreamingDataExampleView extends Div {

    private final ApexCharts chart;
    private Thread thread;

    public StreamingDataExampleView() {

        chart = ApexChartsBuilder.get().withChart(ChartBuilder.get()
                .withType(Type.line)
                .withAnimations(AnimationsBuilder.get()
                        .withEnabled(true)
                        .withEasing(Easing.linear)
                        .withDynamicAnimation(DynamicAnimationBuilder.get()
                                .withSpeed(1000)
                                .build())
                        .build())
                .withToolbar(ToolbarBuilder.get()
                        .withShow(false)
                        .build())
                .withZoom(ZoomBuilder.get().withEnabled(false).build())
                .build())
                .withDataLabels(DataLabelsBuilder.get()
                        .withEnabled(false)
                        .build())
                .withXaxis(XAxisBuilder.get()
                        .withType(XAxisType.datetime)
                        .withTitle(TitleBuilder.get()
                                .withText("Time")
                                .build())
                        .withLabels(LabelsBuilder.get()
                                .withShowDuplicates(false)
                                .withHideOverlappingLabels(false)
                                .withStyle(StyleBuilder.get()
                                        .withCssClass("color")
                                        .build())
                                .withFormatter(FORMARTTER_STRING)
                                .withShow(true)
                                .build())
                        .build())
                .withSeries(new Series<>(0))
                .build();

        chart.setDebug(true);
        chart.setWidthFull();
        chart.setHeight("500px");
        super.add(chart);
    }

    @Override
    protected void onAttach(AttachEvent attachEvent) {
        super.onAttach(attachEvent);
        thread = new Thread(() -> {
            ArrayList<Double> arrayList = new ArrayList<>();
            arrayList.add(0.0);
            while (true) {
                try {
                    Thread.sleep(1000);
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
                final SecureRandom random = new SecureRandom();
                arrayList.add(1 + random.nextDouble());
                getUI().ifPresent(ui -> ui.access(() -> {
                    chart.setLabels(LocalDateTime.now().truncatedTo(ChronoUnit.SECONDS).toString());
                    chart.updateSeries(new Series<>(arrayList.toArray(new Double[]{})));
                }));
            }
        });
        thread.start();
    }

    @Override
    protected void onDetach(DetachEvent detachEvent) {
        super.onDetach(detachEvent);
        thread.interrupt();
    }
}
```

Apparently the time is displayed correctly but, no. I have tried several ways to do it and the graph does not display correctly.

image

**Regards.**

**Pull request merged**
