### PR TITLE
set minimum required jdk11 in pom.xml - fix jitpack.io build

### PR DESCRIPTION
**Pull request by mrgreywater**
Installs node and npm automatically if missing.

This fixes the previously broken jitpack.io build, allowing to directly fetch a compiled nightly build with maven after adding the jitpack repository.

Example usage in pom.xml
```
        <repository>
            <id>jitpack.io</id>
            <url>https://jitpack.io</url>
        </repository>
```
```
        <dependency>
            <groupId>com.github.appreciated</groupId>
            <artifactId>apexcharts-flow</artifactId>
            <version>-SNAPSHOT</version>
        </dependency>
```

### CODE REVIEW

**Comment by TFyre** [comment]
I dont think this should be the default behavior. 

When you are using quarkus+vaadin+apexcharts, the quarkus-vaadin environment already takes care of installing and maintaining your node environment.

This should most likely be configured using a profile.

What do you think?

**Comment by mrgreywater** [comment]
Does it break the build for quarkus-vaadin environment like this?

**Comment by TFyre** [comment]
When Im compiling `apexcharts-flow` project, I dont need this. 

Im not sure what problem you are trying to solve or what issues you are facing. Perhaps you can include some more detail why you need this. Sounds like you are having problems outside of this repo and perhaps should fix it there?

If this is really required, I would be more supportive of using the [vaadin-maven-plugin](https://vaadin.com/docs/latest/configuration/maven) plugin, as thats provided & maintained by vaadin

**Comment by mrgreywater** [comment]
The problem is, on a vanilla system - without node installed - this project will not compile as is. This PR is necessary to make it build on CI systems such as jitpack.io. jitpack.io allows to include this github repo as maven dependency (any commit / branch) without having to compile it yourself or having to push it to the official maven repository.

Here is the compilation log for this repository without the PR: https://jitpack.io/com/github/appreciated/apexcharts-flow/master-c72b288e4b-1/build.log

**Comment by TFyre** [comment]
> Here is the compilation log for this repository without the PR: https://jitpack.io/com/github/appreciated/apexcharts-flow/master-c72b288e4b-1/build.log

The log references a commit from 2020
```
Build starting...
Start: Thu Apr 2 21:25:50 UTC 2020 cfe16a77fe0c
...
[INFO] Building ApexCharts.js 2.0.0.beta9
```

https://jitpack.io/com/github/appreciated/apexcharts-flow/2.0.0-beta13/build.log

Looks like this log is working fine

**Comment by TFyre** [comment]
I can see what the problem is...

Build against current master (with jdk1.8)
https://jitpack.io/com/github/appreciated/apexcharts-flow/master/build.log

Build against current master + [jdk11 changes](https://github.com/TFyre/apexcharts-flow/commit/a83b271ed3d88b13aa63016af3cbe8bbd52c6c4c)
https://jitpack.io/com/github/TFyre/apexcharts-flow/a83b271ed3/build.log

Perhaps you can update the PR to reflect jdk1.8 to jdk11 change?

**Comment by mrgreywater** [comment]
You're right, seems like just updating to java 11 was enough for it to run properly. Cherry picked your commit instead.

**Pull request merged**
