### PR TITLE
Fix Typescript errors

### PR DESCRIPTION
**Pull request by F43nd1r**
I took a stab at #155 and Vaadin 24 compatibility. This basically just adds more type definitions to the code.

### CODE REVIEW

**Comment by F43nd1r** [comment]
@TFyre I have stripped all non-vital changes from the PR.

**Comment by TFyre** [comment]
Happy to merge, can you please squash the commits first?

**Comment by F43nd1r** [comment]
Usually you should be able to squash & merge right on the PR, but sure.

**Comment by TFyre** [comment]
Merged 👍 

TIL!!

**Comment by sishbi** [comment]
@TFyre @F43nd1r Can you help me ?

**Pull request merged**
